substitutions:
  devicename: roode32idf
  friendly_name: ${devicename}

external_components:
  - source: components
    refresh: always

esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: none

api:
  password: !secret api_key

ota:
  platform: esphome
  password: !secret ota_password

logger:
  level: INFO

i2c:
  - id: bus_a
    sda: GPIO21
    scl: GPIO22
    scan: True

vl53l1x:
  sensor_id: 1
  timeout: 2000ms
  pins:
    xshut: GPIO3
    interrupt: GPIO1
  calibration:
    ranging: long

sensor:
  - platform: vl53l1x
    name: "${friendly_name} distance"
    id: tof_distance
    update_interval: 500ms
